// /llms.txt — a plain-text index for LLMs and crawlers, following the
// llms.txt convention (https://llmstxt.org).
//
// Built at request/build time from the Devigo CMS: lists public pages and every
// registered post type. Posts link to their markdown companions
// (/<type>/<slug>.md) generated by src/pages/[type]/[...slug].md.ts so LLMs can
// ingest clean text instead of parsing the rendered page.

import type { APIRoute } from 'astro';
import { devigo, getSettings, siteName, postTypes, NOT_FOUND_SLUG } from '../lib/devigo.js';

export const GET: APIRoute = async (ctx) => {
	const base = ctx.site instanceof URL ? ctx.site : new URL('https://example.com');

	// Fetch everything in parallel; tolerate failures so a single broken
	// resource never blanks the whole file.
	const [settings, pagesList, collections] = await Promise.all([
		getSettings().catch((e) => { console.error('[llms.txt] settings failed:', e); return {}; }),
		devigo.pages.list().catch((e) => { console.error('[llms.txt] pages failed:', e); return []; }),
		Promise.all(
			postTypes.map(async (type) => ({
				type,
				entries: await devigo
					.posts(type)
					.list()
					.then((c) => c.data ?? [])
					.catch((e) => { console.error(`[llms.txt] "${type}" failed:`, e); return []; }),
			})),
		),
	]);

	const companyName = (settings as Record<string, unknown>).company_name as string | undefined;
	const title = companyName || siteName;
	const homeUrl = new URL('/', base).href;

	const lines: string[] = [];
	lines.push(`# ${title}`);
	lines.push('');
	lines.push(`> ${title} website. Canonical URL: ${homeUrl}`);
	lines.push('');

	// Pages (link to HTML — no .md companions are generated for composed pages).
	const pages = (pagesList as any[]).filter((p) => !p.hidden && p.slug !== NOT_FOUND_SLUG);
	if (pages.length) {
		lines.push('## Pages');
		for (const p of pages) {
			const full = await devigo.pages.get(p.slug).catch(() => null);
			const slug = (full?.slug ?? p.slug ?? '').replace(/^\/+|\/+$/g, '');
			const isHome = full?.is_homepage ?? p.is_homepage ?? slug === 'homepage';
			const path = isHome ? '' : slug;
			const url = path ? new URL(`/${path}/`, base).href : homeUrl;
			const name = full?.title_tag ?? p.name ?? slug;
			const desc = full?.meta_description ? `: ${full.meta_description}` : '';
			lines.push(`- [${name}](${url})${desc}`);
		}
		lines.push('');
	}

	// Posts, grouped by post type (link to the markdown companions).
	for (const { type, entries } of collections) {
		if (!entries.length) continue;
		lines.push(`## ${type.charAt(0).toUpperCase() + type.slice(1)}`);
		for (const entry of entries as any[]) {
			const fv: Record<string, unknown> = entry.field_values ?? {};
			const name = pickStr(entry.name, fv.title, fv.text, entry.slug) || entry.slug;
			const excerpt = pickStr(fv.excerpt, fv.text_1, fv.summary, fv.description);
			const mdUrl = new URL(`/${type}/${entry.slug}.md`, base).href;
			const desc = excerpt ? `: ${excerpt.replace(/\n/g, ' ')}` : '';
			lines.push(`- [${name}](${mdUrl})${desc}`);
		}
		lines.push('');
	}

	// Optional reference links.
	lines.push('## Optional');
	lines.push(`- [Sitemap](${new URL('/sitemap-index.xml', base).href})`);
	lines.push(`- [robots.txt](${new URL('/robots.txt', base).href})`);
	lines.push('');

	return new Response(lines.join('\n'), {
		headers: { 'Content-Type': 'text/plain; charset=utf-8' },
	});
};

function pickStr(...vals: unknown[]): string {
	for (const v of vals) {
		if (typeof v === 'string' && v.trim()) return v;
	}
	return '';
}
